FROM scratch
ADD centos-7-docker.tar.xz /

LABEL org.label-schema.schema-version="1.0" \
    org.label-schema.name="CentOS Base Image" \
    org.label-schema.vendor="CentOS" \
    org.label-schema.license="GPLv2" \
    org.label-schema.build-date="20181205"

RUN useradd postgres -d /var/lib/pgsql

RUN echo "postgres" | passwd postgres --stdin

ENV PGHOME /usr/pgsql-11
ENV PGDATABASE postgres
ENV PGUSER postgres
ENV PGPORT 5432
ENV PGLOCALEDIR /usr/pgsql-11/share/locale
ENV MANPATH $MAN_PATH:/usr/pgsql-11/share/man
ENV PGDATA /var/lib/pgsql/11/data
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64
ENV JRE_HOME /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/jre
ENV PATH $PATH:$JAVA_HOME/bin:$JRE_HOME/bin:$JRE_HOME/lib/amdb64:$JRE_HOME/lib/amdb64/server:$PGHOME/bin:$PGHOME/lib
#ENV PATH $PATH:$PGHOME/bin:$PGHOME/lib

RUN set -x; \
yum install -y java-1.8.0-openjdk.x86_64; \
yum install -y gcc\* ;\
#yum install -y epel-release.noarch ;\
yum install -y https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm ;\
yum install -y postgresql11\* --skip-broken;\
yum install -y maven ;\
yum install -y git ;\
yum install -y openssl-devel.x86_64;\
yum install -y sudo;

RUN mkdir -p /usr/pgsql-11/include;\
cp -pR /usr/include/openssl/ /usr/pgsql-11/include/openssl;\
chown postgres:postgres -R /usr/pgsql-11;\

echo -e '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/amd64\n\
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/amd64/server\n\
/usr/pgsql-11/lib\n'\
>>/etc/ld.so.conf; \

#mv /var/lib/pgsql/.bash_profile /var/lib/pgsql/.bash_profile.old ;\

#echo -e '[ -f /etc/profile ] && source /etc/profile\n\
#export PGHOME=/usr/pgsql-11\n\
#export PGDATABASE=postgres\n\
#export PGUSER=postgres\n\
#export PGPORT=5432\n\
#export PGLOCALEDIR=/usr/pgsql-11/share/locale\n\
#export MANPATH=\$MAN_PATH:/usr/pgsql-11/share/man\n\
#PGDATA=/opt/pgsql/11/data\n\
#export PGDATA\n\
## If you want to customize your settings,\n\
## Use the file below. This is not overridden\n\
## by the RPMS.\n\
#[ -f /opt/pgsql/.pgsql_profile ] && source /opt/pgsql/.pgsql_profile\n\
#export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64\n\
#export JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre\n\
#export PATH=\$PATH:\$JAVA_HOME/bin:\$JRE_HOME/bin:\$JRE_HOME/lib/amdb64:\$JRE_HOME/lib/amdb64/server:\$PGHOME/bin:\$PGHOME/lib\n'\
#>>~/.bash_profile; \

#chown postgres:postgres /var/lib/pgsql/.bash_profile; \
#source /var/lib/pgsql/.bash_profile; \

#git clone https://github.com/tada/pljava.git; \
git clone https://github.com/ramujagini/pljava.git; \

chmod -R 777 pljava; \

cd pljava; \

mvn -Pwnosign -Dnar.cores=1 clean install; \

cp -pr /pljava/pljava-so/target/nar/pljava-so-1.6.0-SNAPSHOT-amd64-Linux-gpp-plugin/lib/amd64-Linux-gpp/plugin/libpljava-so-1.6.0-SNAPSHOT.so /usr/pgsql-11/lib/pljava.so; \

cp -pr /pljava/pljava/target/pljava-1.6.0-SNAPSHOT.jar /usr/pgsql-11/share/extension/pljava--1.5.3.jar; \

echo -e "-- Note: as of PL/Java 1.5.0, this file is obsolescent and not needed to install\
-- PL/Java. See "Installing into PostgreSQL" at the project web site for current\
-- installation instructions that do not involve this file. This will eventually\
-- grow out of date and be removed.\
--\
-- You can generate a local copy of the web site with 'mvn site site:stage' and\
-- point a web browser at target/site/staging/install/install.html for the\
-- installation instructions offline.\
\
CREATE SCHEMA sqlj;\
GRANT USAGE ON SCHEMA sqlj TO public;\
\
CREATE FUNCTION sqlj.java_call_handler()\
  RETURNS language_handler AS 'pljava'\
  LANGUAGE C;\
\
CREATE TRUSTED LANGUAGE java HANDLER sqlj.java_call_handler;\
\
CREATE FUNCTION sqlj.javau_call_handler()\
  RETURNS language_handler AS 'pljava'\
  LANGUAGE C;\
\
CREATE LANGUAGE javaU HANDLER sqlj.javau_call_handler;\
\
CREATE TABLE sqlj.jar_repository(\
        jarId           SERIAL PRIMARY KEY,\
        jarName         VARCHAR(100) UNIQUE NOT NULL,\
        jarOrigin   VARCHAR(500) NOT NULL,\
        jarOwner        NAME NOT NULL,\
        jarManifest     TEXT\
);\
GRANT SELECT ON sqlj.jar_repository TO public;\
\
CREATE TABLE sqlj.jar_entry(\
        entryId     SERIAL PRIMARY KEY,\
        entryName       VARCHAR(200) NOT NULL,\
        jarId           INT NOT NULL REFERENCES sqlj.jar_repository ON DELETE CASCADE,\
        entryImage  BYTEA NOT NULL,\
        UNIQUE(jarId, entryName)\
);\
GRANT SELECT ON sqlj.jar_entry TO public;\
\
CREATE TABLE sqlj.jar_descriptor(\
        jarId           INT REFERENCES sqlj.jar_repository ON DELETE CASCADE,\
        ordinal         INT2,\
        PRIMARY KEY (jarId, ordinal),\
        entryId     INT NOT NULL REFERENCES sqlj.jar_entry ON DELETE CASCADE\
);\
GRANT SELECT ON sqlj.jar_descriptor TO public;\
\
CREATE TABLE sqlj.classpath_entry(\
        schemaName      VARCHAR(30) NOT NULL,\
        ordinal         INT2 NOT NULL,\
        jarId           INT NOT NULL REFERENCES sqlj.jar_repository ON DELETE CASCADE,\
        PRIMARY KEY(schemaName, ordinal)\
);\
GRANT SELECT ON sqlj.classpath_entry TO public;\
\
CREATE TABLE sqlj.typemap_entry(\
        mapId           SERIAL PRIMARY KEY,\
        javaName        VARCHAR(200) NOT NULL,\
        sqlName         NAME NOT NULL\
);\
GRANT SELECT ON sqlj.typemap_entry TO public;\
\
CREATE FUNCTION sqlj.install_jar(VARCHAR, VARCHAR, BOOLEAN) RETURNS void\
        AS 'org.postgresql.pljava.management.Commands.installJar'\
        LANGUAGE java SECURITY DEFINER;\
\
CREATE FUNCTION sqlj.install_jar(BYTEA, VARCHAR, BOOLEAN) RETURNS void\
        AS 'org.postgresql.pljava.management.Commands.installJar'\
        LANGUAGE java SECURITY DEFINER;\
\
CREATE FUNCTION sqlj.replace_jar(VARCHAR, VARCHAR, BOOLEAN) RETURNS void\
        AS 'org.postgresql.pljava.management.Commands.replaceJar'\
        LANGUAGE java SECURITY DEFINER;\
\
CREATE FUNCTION sqlj.replace_jar(BYTEA, VARCHAR, BOOLEAN) RETURNS void\
        AS 'org.postgresql.pljava.management.Commands.replaceJar'\
        LANGUAGE java SECURITY DEFINER;\
\
CREATE FUNCTION sqlj.remove_jar(VARCHAR, BOOLEAN) RETURNS void\
        AS 'org.postgresql.pljava.management.Commands.removeJar'\
        LANGUAGE java SECURITY DEFINER;\
\
CREATE FUNCTION sqlj.set_classpath(VARCHAR, VARCHAR) RETURNS void\
        AS 'org.postgresql.pljava.management.Commands.setClassPath'\
        LANGUAGE java SECURITY DEFINER;\
\
CREATE FUNCTION sqlj.get_classpath(VARCHAR) RETURNS VARCHAR\
        AS 'org.postgresql.pljava.management.Commands.getClassPath'\
        LANGUAGE java STABLE SECURITY DEFINER;\
\
CREATE FUNCTION sqlj.add_type_mapping(VARCHAR, VARCHAR) RETURNS void\
        AS 'org.postgresql.pljava.management.Commands.addTypeMapping'\
        LANGUAGE java SECURITY DEFINER;\
\
CREATE FUNCTION sqlj.drop_type_mapping(VARCHAR) RETURNS void\
        AS 'org.postgresql.pljava.management.Commands.dropTypeMapping'\
        LANGUAGE java SECURITY DEFINER;"\
>/usr/pgsql-11/share/extension/pljava--1.5.3.sql

RUN echo -e "# pljava extension\n\
comment = 'PL/Java bundled as an extension'\n\
default_version = '1.5.3'\n\
relocatable = false\n"\
>/usr/pgsql-11/share/extension/pljava.control; \

echo -e 'postgres' >$PGHOME/pass.conf; \

sudo su - postgres -c "$PGHOME/bin/initdb --pwfile $PGHOME/pass.conf -U postgres -E utf8 -D $PGDATA" ;\
echo "host    all             all             0.0.0.0/0            trust" >> $PGDATA/pg_hba.conf ;\

echo -e "dynamic_library_path= '/usr/pgsql-11/lib:\$libdir'\n\
pljava.classpath= '/usr/pgsql-11/share/extension/pljava--1.5.3.jar'\n\
pljava.vmoptions = '-Xms32M -Xmx64M -XX:ParallelGCThreads=2'\n\
pljava.libjvm_location = '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/jre/lib/amd64/server/libjvm.so'\n\
listen_addresses = '*'\n"\
>> $PGDATA/postgresql.conf;

#RUN sudo su - postgres -c "$PGHOME/bin/pg_ctl stop -mf"; \
RUN sudo su - postgres -c "$PGHOME/bin/pg_ctl start -D $PGDATA"; \
sudo su - postgres -c "$PGHOME/bin/psql -c 'create EXTENSION pljava';"; \
exit

CMD ["/bin/bash"]